# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.15.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/pedroppinheiro/fwf
    
    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved
      BIN: /tmp/bin # path to where test results will be saved
    
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: mkdir -p $TEST_RESULTS # create the test results directory
      - run: mkdir -p $BIN # create the test results directory
      
      - run: go env
      - run: go get -v -t -d ./...

      - run: "gotestsum --junitfile $TEST_RESULTS/gotestsum-report.xml"
        #- run: go test -v ./...

      - run: GOOS=linux GOARCH=amd64 go build -o $BIN
      - run: GOOS=windows GOARCH=amd64 go build -o $BIN

      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/bin
          destination: bin

      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results
      
